spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 2Mb
      max-request-size: 2Mb
      enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appointment_service
    username: root
    password: password
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 591443185387-qdtad05ht559s784cab89hi4sa3pph6u.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
              - openid
          github:
            clientId: 2f5c81edda04b7048d37
            clientSecret: a7bfc0c15487cd25d4a4ef228e99092e64ba2353
            scope:
              - user:email
              - profile
          facebook:
            client-id: 688353402927229
            client-secret: 4815b00c9443ca6ff108f515ce2b5aea
            scope:
              - public_profile
              - email
          poc-client:
            client-id: poc-client
            client-secret: WfIbtDAcXDV9JTkuH8bDPgqs2C2yq90s
            client-name: poc-client
            redirect-uri: http://localhost:8082/login/oauth2/code/poc-client
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          poc-client:
            issuer-uri: http://localhost:8081/realms/poc-realm
server:
  port: 8082



